version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: import-large-csv
    env_file:
      - .env # ensure to create .env file in the ci/cd pipeline
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
